# Generated by Django 5.2.13 on 2026-04-22 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("invoices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule_code",
                    models.CharField(
                        choices=[
                            ("MISSING_PAYMENT", "Invoice issued but payment missing"),
                            (
                                "NO_INVOICE",
                                "Active subscription — no invoice generated",
                            ),
                            ("UNDERBILLING", "Billed amount < contracted amount"),
                            ("DUPLICATE_REFUND", "Duplicate refund detected"),
                            ("ABNORMAL_DISCOUNT", "Discount ratio above threshold"),
                            ("MISSING_RENEWAL", "Contract renewal overdue"),
                            ("PAYMENT_DELAY", "Payment received after due date"),
                            (
                                "CONTRACT_MISMATCH",
                                "Billing does not match contract terms",
                            ),
                            (
                                "FAILED_PAYMENT_STREAK",
                                "Multiple consecutive failed payments",
                            ),
                            ("ZERO_REVENUE", "Active customer — zero revenue period"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                (
                    "leakage_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_alerts",
                        to="customers.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rule_alerts",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "rule_alerts",
            },
        ),
        migrations.CreateModel(
            name="LeakageCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_number",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("confirmed", "Confirmed"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                            ("escalated", "Escalated"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "estimated_leakage_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "confirmed_leakage_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leakage_cases",
                        to="customers.customer",
                    ),
                ),
                (
                    "rule_alerts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="leakage_cases",
                        to="leakage_cases.rulealert",
                    ),
                ),
            ],
            options={
                "db_table": "leakage_cases",
            },
        ),
        migrations.AddIndex(
            model_name="rulealert",
            index=models.Index(
                fields=["customer", "rule_code"], name="rule_alerts_custome_7778a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rulealert",
            index=models.Index(
                fields=["severity", "is_resolved"],
                name="rule_alerts_severit_603928_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rulealert",
            index=models.Index(
                fields=["detected_at"], name="rule_alerts_detecte_6ad3a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leakagecase",
            index=models.Index(
                fields=["customer", "status"], name="leakage_cas_custome_c14456_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leakagecase",
            index=models.Index(
                fields=["priority", "status"], name="leakage_cas_priorit_58ef1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leakagecase",
            index=models.Index(
                fields=["created_at"], name="leakage_cas_created_d2e3ab_idx"
            ),
        ),
    ]
