# Generated by Django 5.2.13 on 2026-04-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="US", max_length=100)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("enterprise", "Enterprise"),
                            ("mid_market", "Mid-Market"),
                            ("smb", "SMB"),
                            ("startup", "Startup"),
                        ],
                        default="smb",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("churned", "Churned"),
                            ("suspended", "Suspended"),
                            ("prospect", "Prospect"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("acquisition_date", models.DateField()),
                ("churn_date", models.DateField(blank=True, null=True)),
                ("account_manager", models.CharField(blank=True, max_length=255)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("risk_tier", models.CharField(default="medium", max_length=20)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "customers",
                "indexes": [
                    models.Index(
                        fields=["status", "segment"], name="customers_status_f0c408_idx"
                    ),
                    models.Index(
                        fields=["acquisition_date"], name="customers_acquisi_3cb8c3_idx"
                    ),
                ],
            },
        ),
    ]
