# Generated by Django 5.2.13 on 2026-04-22 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("customers", "0001_initial"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("void", "Void"),
                            ("written_off", "Written Off"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(db_index=True)),
                ("due_date", models.DateField(db_index=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("billing_address", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="contracts.contract",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="customers.customer",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "indexes": [
                    models.Index(
                        fields=["customer", "status"],
                        name="invoices_custome_90a13d_idx",
                    ),
                    models.Index(
                        fields=["issue_date", "due_date"],
                        name="invoices_issue_d_f0e5fb_idx",
                    ),
                    models.Index(
                        fields=["status", "due_date"], name="invoices_status_73cf28_idx"
                    ),
                ],
            },
        ),
    ]
