# Generated by Django 5.2.13 on 2026-04-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForecastResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_name",
                    models.CharField(
                        choices=[("prophet", "Prophet"), ("sarima", "SARIMA")],
                        default="prophet",
                        max_length=20,
                    ),
                ),
                ("model_version", models.CharField(default="v1", max_length=50)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("collections", "Collections"),
                            ("renewals", "Renewals"),
                            ("mrr", "MRR"),
                        ],
                        default="revenue",
                        max_length=20,
                    ),
                ),
                (
                    "period_month",
                    models.CharField(db_index=True, help_text="YYYY-MM", max_length=7),
                ),
                (
                    "forecasted_value",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "lower_bound",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "upper_bound",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("deviation_pct", models.FloatField(blank=True, null=True)),
                ("is_anomalous", models.BooleanField(db_index=True, default=False)),
                ("anomaly_threshold_pct", models.FloatField(default=15.0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "forecast_results",
                "indexes": [
                    models.Index(
                        fields=["metric", "period_month"],
                        name="forecast_re_metric_9fa143_idx",
                    ),
                    models.Index(
                        fields=["is_anomalous"], name="forecast_re_is_anom_0a03b4_idx"
                    ),
                ],
                "unique_together": {
                    ("model_name", "metric", "period_month", "model_version")
                },
            },
        ),
    ]
