# Generated by Django 5.2.13 on 2026-04-22 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                            ("trial", "Trial"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "mrr",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly Recurring Revenue",
                        max_digits=12,
                    ),
                ),
                (
                    "arr",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual Recurring Revenue",
                        max_digits=14,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("trial_end_date", models.DateField(blank=True, null=True)),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=255)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="contracts.contract",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="customers.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="contracts.product",
                    ),
                ),
                (
                    "upgrade_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upgrades",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "indexes": [
                    models.Index(
                        fields=["customer", "status"],
                        name="subscriptio_custome_34b933_idx",
                    ),
                    models.Index(
                        fields=["next_billing_date"],
                        name="subscriptio_next_bi_72377a_idx",
                    ),
                    models.Index(
                        fields=["product", "status"],
                        name="subscriptio_product_5bacd0_idx",
                    ),
                ],
            },
        ),
    ]
