# Generated by Django 5.2.13 on 2026-04-22 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("ach", "ACH"),
                            ("wire", "Wire"),
                            ("check", "Check"),
                            ("crypto", "Crypto"),
                        ],
                        default="credit_card",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("payment_date", models.DateField(db_index=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("attempt_count", models.PositiveSmallIntegerField(default=1)),
                ("is_late", models.BooleanField(default=False)),
                ("days_late", models.IntegerField(default=0)),
                ("processor", models.CharField(blank=True, max_length=100)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="customers.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "indexes": [
                    models.Index(
                        fields=["customer", "status"],
                        name="payments_custome_04132e_idx",
                    ),
                    models.Index(
                        fields=["payment_date"], name="payments_payment_aebcb7_idx"
                    ),
                    models.Index(
                        fields=["invoice", "status"], name="payments_invoice_58a325_idx"
                    ),
                ],
            },
        ),
    ]
