# Generated by Django 5.2.13 on 2026-04-22 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_version", models.CharField(default="v1", max_length=50)),
                (
                    "score",
                    models.FloatField(
                        help_text="Isolation Forest raw score (lower = more anomalous)"
                    ),
                ),
                ("is_anomaly", models.BooleanField(db_index=True, default=False)),
                ("threshold_used", models.FloatField(default=-0.1)),
                ("feature_snapshot", models.JSONField(blank=True, default=dict)),
                ("scored_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "period_month",
                    models.CharField(blank=True, help_text="YYYY-MM", max_length=7),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_scores",
                        to="customers.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomaly_scores",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "anomaly_scores",
                "indexes": [
                    models.Index(
                        fields=["customer", "is_anomaly"],
                        name="anomaly_sco_custome_952858_idx",
                    ),
                    models.Index(
                        fields=["scored_at"], name="anomaly_sco_scored__b95416_idx"
                    ),
                ],
            },
        ),
    ]
