# Generated by Django 5.2.13 on 2026-04-22 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0001_initial"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyRevenueSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_month",
                    models.CharField(
                        db_index=True, help_text="YYYY-MM", max_length=7, unique=True
                    ),
                ),
                (
                    "total_invoiced",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_collected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_refunded",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_discounted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "net_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("active_subscriptions", models.IntegerField(default=0)),
                ("new_customers", models.IntegerField(default=0)),
                ("churned_customers", models.IntegerField(default=0)),
                ("failed_payment_count", models.IntegerField(default=0)),
                (
                    "leakage_estimated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("collection_rate", models.FloatField(default=0.0)),
            ],
            options={
                "db_table": "monthly_revenue_summaries",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                            ("promotional", "Promotional"),
                            ("loyalty", "Loyalty"),
                            ("negotiated", "Negotiated"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("approved_by", models.CharField(blank=True, max_length=255)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "discounts",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("SCORE", "Score"),
                            ("ALERT", "Alert"),
                            ("RESOLVE", "Resolve"),
                            ("INGEST", "Ingest"),
                            ("TRAIN", "Train"),
                            ("FORECAST", "Forecast"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=100)),
                ("entity_id", models.CharField(db_index=True, max_length=128)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_logs_entity__d4c2e5_idx",
                    ),
                    models.Index(
                        fields=["occurred_at"], name="audit_logs_occurre_cdf79f_idx"
                    ),
                    models.Index(
                        fields=["user", "action"], name="audit_logs_user_id_d685f3_idx"
                    ),
                ],
            },
        ),
    ]
