# Generated by Django 5.2.13 on 2026-04-22 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("logistic_regression", "Logistic Regression"),
                            ("xgboost", "XGBoost"),
                            ("ensemble", "Ensemble"),
                        ],
                        default="xgboost",
                        max_length=30,
                    ),
                ),
                ("model_version", models.CharField(default="v1", max_length=50)),
                ("leakage_probability", models.FloatField(help_text="0.0 – 1.0")),
                (
                    "risk_severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("rank_percentile", models.FloatField(blank=True, null=True)),
                ("feature_snapshot", models.JSONField(blank=True, default=dict)),
                ("shap_values", models.JSONField(blank=True, default=dict)),
                ("top_features", models.JSONField(blank=True, default=list)),
                ("scored_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "period_month",
                    models.CharField(blank=True, help_text="YYYY-MM", max_length=7),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_scores",
                        to="customers.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_scores",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "risk_scores",
                "indexes": [
                    models.Index(
                        fields=["customer", "risk_severity"],
                        name="risk_scores_custome_f4a879_idx",
                    ),
                    models.Index(
                        fields=["leakage_probability"],
                        name="risk_scores_leakage_0e4aae_idx",
                    ),
                    models.Index(
                        fields=["scored_at"], name="risk_scores_scored__c0dcb8_idx"
                    ),
                ],
            },
        ),
    ]
